#                   This is a work in progress

<b><span style="color:red">To begin:</span></b><br>
<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></b></i>

In [2]:
import IPython.display as ipd
ipd.Audio(filename='resources/cell001.ogg', rate=44100, autoplay=False)

# Disclamer

I am not a math expert.  I am teaching myself linear algebra and keeping a notebook of what I've learned.  My focus is on the mathematics but I test and demonstrate the math using the python programming language.  Nothing here should be accepted as 100% correct.  I am a mathematics amateur.

I'm using the following resources as my self-study guides:

1.  Linear Algebra Step by Step, Kuldeep Singh, Oxford University Press. [Kindle Edition](https://www.amazon.com/gp/product/B07XGF2G87/ref=ppx_yo_dt_b_d_asin_title_o00?ie=UTF8&psc=1).
2.  Basics of Linear Algebra for Machine Learning, [Jason Brownlee](https://machinelearningmastery.com/), self-published PDF.
3.  [3Blue1Brown.com](https://www.3blue1brown.com/) Linear Algebra YouTube series.
4.  [Khan Academy](https://www.khanacademy.org/math/linear-algebra) Math: Linear algebra.

Linear Algebra is the study of linear equations, vectors, matrices, and their transformations.  An equation is where two mathematical expressions are defined as being equal.

$A = V/R$ &nbsp;  or &nbsp;  $x + 2y + z = 5$ &nbsp;  or &nbsp;  $x^2 − 1 = 0$ 

An equation is linear when none of its variables (unknowns) are raised to any power other than 1 or 0.

$x + 2y = 5$ &nbsp;   or &nbsp; $x = 7$ &nbsp;  or &nbsp;  $2x + y + z + w = −5$ 

Remember any number or variable raised to the first power equals that number itself, and any number or variable raised to the zero power equals one.  We usually leave off the one when something is raised to the first power.

$x^0 = 1$ &nbsp;  and &nbsp;  $y^1 = y$ &nbsp;  but &nbsp; $z^2 = z \times z$

$x + 2y + z = 5$ &nbsp; is a linear equation, but neither &nbsp; $x^2 − 1 = 0$ &nbsp; or &nbsp;  $sin(x) − y + z = 3$ &nbsp; are linear.


NumPy is a Python library that is used for numerical and scientific computing and is well suited for linear algebra.  To use the NumPy library we must first **import** it into our program.  Library imports are usually placed at the top of the program.

<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></b></i></br>
    <span style="color:blue"><i>However the cell below does not display any output.</i></span>

In [3]:
import numpy as np 

NumPy gives us many different ways to create an array.  The easiest way is to simply pass the NumPy array() function a list of items.  The list can be statically entered as showen below or the list could be stored in a variable.  Later we'll learn how to create an array by reading data from a file.

<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></i></b>
    <span style="color:blue">Observe the output beneth the cell that the python code produced.</span>
    

In [4]:
A = np.array([1,2,3,4])
print("Array 'A' is",A,"\n")
print("The shape of array 'A' is", A.shape, "because it has", A.size, "elements in 1 row.")
print("Each element of the array is type", A.dtype, " This array only has", A.ndim,"dimention.\n")

A = np.array([[1,2],[3,4]])
print("But with a few minor changes the array becomes\n",A)
print("The shape of this array is", A.shape, "because it has 2 rows and 2 columns.")
print("This array has a total of", A.size, "elements each of which are type",A.dtype)
print("This is a", A.ndim,"dimentional array.")

#ipd.Audio(filename='/Users/clydehoadley/Music/temp/cell001.mp3', rate=44100, autoplay=True)

Array 'A' is [1 2 3 4] 

The shape of array 'A' is (4,) because it has 4 elements in 1 row.
Each element of the array is type int64  This array only has 1 dimention.

But with a few minor changes the array becomes
 [[1 2]
 [3 4]]
The shape of this array is (2, 2) because it has 2 rows and 2 columns.
This array has a total of 4 elements each of which are type int64
This is a 2 dimentional array.


The **zeros()** function creates a new array of given dimentions and fills it with zeros. The **zeros()** function accepts a tuple that specifies the dimensions of the array to create.  It can optionally accept a data type for the new array.

<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></i></b>

In [5]:
a = np.zeros((3,1))
print(a, " A 3x1 vertical vector having shape",a.shape,"\n")
a = np.zeros((1,3),dtype=np.int)
print(a, " A 1x3 horizontal integer vector having shape",a.shape,"\n")
a = np.zeros((3,3))
print(a, " A 3x3 two dimentional square matrix having shape",a.shape)

[[0.]
 [0.]
 [0.]]  A 3x1 vertical vector having shape (3, 1) 

[[0 0 0]]  A 1x3 horizontal integer vector having shape (1, 3) 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]  A 3x3 two dimentional square matrix having shape (3, 3)


Given two or more existing arrays, you can stack them vertically using the **vstack()** function. For example, given two one-dimensional arrays, you can create a new **two-dimensional** array with two rows by vertically stacking one on top of the other.

Or with two or more existing arrays, you can stack them horizontally using the **hstack()** function. For example, given two one-dimensional arrays, you can create a new **one-dimensional** array or one row with the columns of the first and second arrays concatenated.

In [6]:
a = np.array([1, 2, 3]) # create two 1x3 arrays
b = np.array([4, 5, 6])
c = np.array([77, 88, 99])
print("a = ", a, "\n")
print("b = ", b, "\n")
print("c = ", c, "\n")
print(np.vstack((b,a)), "vstack 'b' on top of 'a' giving shape", np.vstack((a,b)).shape,"\n")
print(np.hstack((c,a,b)), "hstack (attach) 'b' onto the end of 'c'")
print("                             and 'a' onto the end of 'b' giving shape", np.hstack((a,b)).shape)

a =  [1 2 3] 

b =  [4 5 6] 

c =  [77 88 99] 

[[4 5 6]
 [1 2 3]] vstack 'b' on top of 'a' giving shape (2, 3) 

[77 88 99  1  2  3  4  5  6] hstack (attach) 'b' onto the end of 'c'
                             and 'a' onto the end of 'b' giving shape (6,)


In [7]:
# 3 additional NumPy functions for creating arrays.

# Create a new array of your choice of shape and fill it with the value you specify.
F = np.full((4, 2), 42)
print(F, "= F with shape", F.shape, "\n")
F2 = np.full_like(F, 24)
print(F2, "= F2 with shape", F2.shape, "\n")

# Create array filled with numbers starting with 5 goint up to 50 but count by 5's
r = np.arange (5,50,5,dtype=int)
print("r = ", r, "\n")

# Create an array filled with numbers starting with 3 going up to 222 but not more than
# fifty elements (columns.)  Do not include the ending number
l = np.linspace(3, 222, endpoint=False, dtype=int)
print("l = ", l, "\n")
# Create an array filled with numbers starting with 2 going up to 333 but not more than
# thirty elements (columns) and include the ending number. 
l2 = np.linspace(2, 333, num=30, endpoint=True, dtype=int)
print("l2 = ", l2)

[[42 42]
 [42 42]
 [42 42]
 [42 42]] = F with shape (4, 2) 

[[24 24]
 [24 24]
 [24 24]
 [24 24]] = F2 with shape (4, 2) 

r =  [ 5 10 15 20 25 30 35 40 45] 

l =  [  3   7  11  16  20  24  29  33  38  42  46  51  55  59  64  68  73  77
  81  86  90  94  99 103 108 112 116 121 125 130 134 138 143 147 151 156
 160 165 169 173 178 182 186 191 195 200 204 208 213 217] 

l2 =  [  2  13  24  36  47  59  70  81  93 104 116 127 138 150 161 173 184 196
 207 218 230 241 253 264 275 287 298 310 321 333]


In [8]:
# 3 additional NumPy functions for combining arrays.

# dstack Takes a sequence of arrays and stack them along the 
# third axis to make a single array.
a = np.array([1, 2, 3, 22])
b = np.array([4, 5, 6, 33])
print(np.dstack((a,b)), "= dstack\n" )

# Join a sequence of arrays along an EXISTING axis.
a = np.array([[11, 12], [13, 44]])
b = np.array([[14, 15], [16, 55]])
print(np.concatenate((a,b),axis=0),"concatenate on axis=0 (vertical axis)\n")
print(np.concatenate((a,b),axis=1),"concatenate on axis=1 (horizontal axis)\n")

# Join a sequence of arrays along a NEW axis.
c = np.arange(1,8)
d = np.arange(9,16)
e = np.arange(17,24)
print("c =",c, "\n")
print("d =",d, "\n")
print("e =",e, "\n")
print(np.stack((c,d,e), axis=0), "stack arrays along axis=0 (row wise)\n")
print(np.stack((c,d,e), axis=1),"stack arrays along axis=1 (column wise)\n")
# print(np.stack((c,d,e), axis=2)) #axis 2 is out of bounds for array of dimension 2

[[[ 1  4]
  [ 2  5]
  [ 3  6]
  [22 33]]] = dstack

[[11 12]
 [13 44]
 [14 15]
 [16 55]] concatenate on axis=0 (vertical axis)

[[11 12 14 15]
 [13 44 16 55]] concatenate on axis=1 (horizontal axis)

c = [1 2 3 4 5 6 7] 

d = [ 9 10 11 12 13 14 15] 

e = [17 18 19 20 21 22 23] 

[[ 1  2  3  4  5  6  7]
 [ 9 10 11 12 13 14 15]
 [17 18 19 20 21 22 23]] stack arrays along axis=0 (row wise)

[[ 1  9 17]
 [ 2 10 18]
 [ 3 11 19]
 [ 4 12 20]
 [ 5 13 21]
 [ 6 14 22]
 [ 7 15 23]] stack arrays along axis=1 (column wise)



In [9]:
from numpy import array
# define array
data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])

split = 2
# separate data
training, testing = data[:split, :], data[split:,:] 
print(testing.shape, "testing shape\n")
print(testing, "= testing\n\n")
print(training.shape,"training shape before\n")
print(training, "= training before.\n")

training=training.reshape((training.shape[0],training.shape[1],1))

print(training.shape,"training shape after\n")
print(training,"= training after.\n")


(1, 3) testing shape

[[77 88 99]] = testing


(2, 3) training shape before

[[11 22 33]
 [44 55 66]] = training before.

(2, 3, 1) training shape after

[[[11]
  [22]
  [33]]

 [[44]
  [55]
  [66]]] = training after.



In [10]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
A = array([[1, 2, 3],
          [4, 5, 6]])
print(A,"=A\n")
# define scalar
b = array([7,8,9])
print(b,"=b\n")
# broadcast 
c=A+b 
print(c,"=C\n")

[[1 2 3]
 [4 5 6]] =A

[7 8 9] =b

[[ 8 10 12]
 [11 13 15]] =C



In [11]:
# Broadcasting is arithmatic performed on arrays of different sizes
# define array
A = array([[1, 2,33],
          [4, 5,44]])
print(A,"=A",A.shape,"\n")
# define scalar
b = array([7,8,9])
print(b,"=b",b.shape,"\n")  #this shape can be added to array A

b = array([[7,8,9],
         [9,8,7]])
print(b,"=b",b.shape,"\n")   #this shape can be added to array A

#b = array([[7,8],
#         [9,8]])
print(b,"=b",b.shape,"\n")  # Error

#b = array([7,8])
print(b,"=b",b.shape,"\n")  # Error
# broadcast 

c=A+b 
print(c,"=C",c.shape,"\n")

[[ 1  2 33]
 [ 4  5 44]] =A (2, 3) 

[7 8 9] =b (3,) 

[[7 8 9]
 [9 8 7]] =b (2, 3) 

[[7 8 9]
 [9 8 7]] =b (2, 3) 

[[7 8 9]
 [9 8 7]] =b (2, 3) 

[[ 8 10 42]
 [13 13 51]] =C (2, 3) 



In [12]:
# Finding the Norm of a vector

from numpy import array
v=array([1,2,3,4])

from numpy.linalg import norm
print("L1=",norm(v,1))
print("L2=",norm(v))

from numpy import inf
print("Linf=",norm(v,inf),"\n\n")

#compute manually 
import math as mt
print("L1=",abs(v[0]) + abs(v[1]) + abs(v[2]) + abs(v[3]))
print("L2=",mt.sqrt( (v[0]**2 + v[1]**2 + v[2]**2 + v[3]**2)))  # ** is raise to power, so **2 is the square
m=-1
for i in range(0,4) :
    if abs(v[i]) > m : m=v[i]
print("Linf=",m)

L1= 10.0
L2= 5.477225575051661
Linf= 4.0 


L1= 10
L2= 5.477225575051661
Linf= 4
