<b><span style="color:red">To begin:</span></b><br>
<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></b></i>

In [ ]:
#import IPython.display as ipd
#ipd.Audio(filename='/Users/clydehoadley/Music/temp/cell001.mp3', rate=44100, autoplay=True)

<font size="4">NumPy is a Python library that is used for numerical and scientific computing and is well suited for linear algebra.  To use the NumPy library we must first **import** it into our program.  Library imports are usually placed at the top of the program.</font>

<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></b></i></br>
    <span style="color:blue"><i>However the cell below does not display any output.</i></span>

In [ ]:
import numpy as np 

<font size="4">NumPy gives us many different ways to create an array.  The easiest way is to simply pass the NumPy array() function a list of items.  The list can be statically entered as showen below or the list could be stored in a variable.  Later we'll learn how to create an array by reading data from a file.</font>

<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></i></b>
    <span style="color:blue">Observe the output beneth the cell that the python code produced.</span>
    

In [ ]:
A = np.array([1,2,3,4])
print("Array 'A' is",A,"\n")
print("The shape of array 'A' is", A.shape, "because it has", A.size, "elements in 1 row.")
print("Each element of the array is type", A.dtype, " This array only has", A.ndim,"dimention.\n")

A = np.array([[1,2],[3,4]])
print("But with a few minor changes the array becomes\n",A)
print("The shape of this array is", A.shape, "because it has 2 rows and 2 columns.")
print("This array has a total of", A.size, "elements each of which are type",A.dtype)
print("This is a", A.ndim,"dimentional array.")

#ipd.Audio(filename='/Users/clydehoadley/Music/temp/cell001.mp3', rate=44100, autoplay=True)

<font size="4">The **zeros()** function creates a new array of given dimentions and fills it with zeros. The **zeros()** function accepts a tuple that specifies the dimensions of the array to create.  It can optionally accept a data type for the new array.</font>

<b><i>Place your mouse pointer anywhere in the shaded area below then hold down the
    \< Shift \> key and press \< Enter \></i></b>

In [ ]:
a = np.zeros((3,1))
print(a, " A 3x1 vertical vector having shape",a.shape,"\n")
a = np.zeros((1,3),dtype=np.int)
print(a, " A 1x3 horizontal integer vector having shape",a.shape,"\n")
a = np.zeros((3,3))
print(a, " A 3x3 two dimentional square matrix having shape",a.shape)

<font size="4">Given two or more existing arrays, you can stack them vertically using the **vstack()** function. For example, given two one-dimensional arrays, you can create a new **two-dimensional** array with two rows by vertically stacking one on top of the other.

Or with two or more existing arrays, you can stack them horizontally using the **hstack()** function. For example, given two one-dimensional arrays, you can create a new **one-dimensional** array or one row with the columns of the first and second arrays concatenated.</font>

In [ ]:
a = np.array([1, 2, 3]) # create two 1x3 arrays
b = np.array([4, 5, 6])
c = np.array([77, 88, 99])
print("a = ", a, "\n")
print("b = ", b, "\n")
print("c = ", c, "\n")
print(np.vstack((b,a)), "vstack 'b' on top of 'a' giving shape", np.vstack((a,b)).shape,"\n")
print(np.hstack((c,a,b)), "hstack (attach) 'b' onto the end of 'c'")
print("                             and 'a' onto the end of 'b' giving shape", np.hstack((a,b)).shape)

In [ ]:
# 3 additional NumPy functions for creating arrays.

# Create a new array of your choice of shape and fill it with the value you specify.
F = np.full((4, 2), 42)
print(F, "= F with shape", F.shape, "\n")
F2 = np.full_like(F, 24)
print(F2, "= F2 with shape", F2.shape, "\n")

# Create array filled with numbers starting with 5 goint up to 50 but count by 5's
r = np.arange (5,50,5,dtype=int)
print("r = ", r, "\n")

# Create an array filled with numbers starting with 3 going up to 222 but not more than
# fifty elements (columns.)  Do not include the ending number
l = np.linspace(3, 222, endpoint=False, dtype=int)
print("l = ", l, "\n")
# Create an array filled with numbers starting with 2 going up to 333 but not more than
# thirty elements (columns) and include the ending number. 
l2 = np.linspace(2, 333, num=30, endpoint=True, dtype=int)
print("l2 = ", l2)

In [ ]:
# 3 additional NumPy functions for combining arrays.

# dstack Takes a sequence of arrays and stack them along the 
# third axis to make a single array.
a = np.array([1, 2, 3, 22])
b = np.array([4, 5, 6, 33])
print(np.dstack((a,b)), "= dstack\n" )

# Join a sequence of arrays along an EXISTING axis.
a = np.array([[11, 12], [13, 44]])
b = np.array([[14, 15], [16, 55]])
print(np.concatenate((a,b),axis=0),"concatenate on axis=0 (vertical axis)\n")
print(np.concatenate((a,b),axis=1),"concatenate on axis=1 (horizontal axis)\n")

# Join a sequence of arrays along a NEW axis.
c = np.arange(1,8)
d = np.arange(9,16)
e = np.arange(17,24)
print("c =",c, "\n")
print("d =",d, "\n")
print("e =",e, "\n")
print(np.stack((c,d,e), axis=0), "stack arrays along axis=0 (row wise)\n")
print(np.stack((c,d,e), axis=1),"stack arrays along axis=1 (column wise)\n")
# print(np.stack((c,d,e), axis=2)) #axis 2 is out of bounds for array of dimension 2

In [ ]:
from numpy import array
# define array
data = array([
  [11, 22, 33],
  [44, 55, 66],
  [77, 88, 99]])

split = 2
# separate data
training, testing = data[:split, :], data[split:,:] 
print(testing.shape, "testing shape\n")
print(testing, "= testing\n\n")
print(training.shape,"training shape before\n")
print(training, "= training before.\n")

training=training.reshape((training.shape[0],training.shape[1],1))

print(training.shape,"training shape after\n")
print(training,"= training after.\n")


In [12]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
A = array([[1, 2, 3],
          [4, 5, 6]])
print(A,"=A\n")
# define scalar
b = array([7,8,9])
print(b,"=b\n")
# broadcast 
c=A+b 
print(c,"=C\n")

[[1 2 3]
 [4 5 6]] =A

[7 8 9] =b

[[ 8 10 12]
 [11 13 15]] =C



In [26]:
# Broadcasting is arithmatic performed on arrays of different sizes
# define array
A = array([[1, 2,33],
          [4, 5,44]])
print(A,"=A",A.shape,"\n")
# define scalar
b = array([7,8,9])
print(b,"=b",b.shape,"\n")  #this shape can be added to array A

b = array([[7,8,9],
         [9,8,7]])
print(b,"=b",b.shape,"\n")   #this shape can be added to array A

#b = array([[7,8],
#         [9,8]])
print(b,"=b",b.shape,"\n")  # Error

#b = array([7,8])
print(b,"=b",b.shape,"\n")  # Error
# broadcast 

c=A+b 
print(c,"=C",c.shape,"\n")

[[ 1  2 33]
 [ 4  5 44]] =A (2, 3) 

[7 8 9] =b (3,) 

[[7 8 9]
 [9 8 7]] =b (2, 3) 

[[7 8 9]
 [9 8 7]] =b (2, 3) 

[[7 8 9]
 [9 8 7]] =b (2, 3) 

[[ 8 10 42]
 [13 13 51]] =C (2, 3) 



In [46]:
# Finding the Norm of a vector

from numpy import array
v=array([1,2,3,4])

from numpy.linalg import norm
print("L1=",norm(v,1))
print("L2=",norm(v))

from numpy import inf
print("Linf=",norm(v,inf),"\n\n")

#compute manually 
import math as mt
print("L1=",abs(v[0]) + abs(v[1]) + abs(v[2]) + abs(v[3]))
print("L2=",mt.sqrt( (v[0]**2 + v[1]**2 + v[2]**2 + v[3]**2)))  # ** is raise to power, so **2 is the square
m=-1
for i in range(0,4) :
    if abs(v[i]) > m : m=v[i]
print("Linf=",m)

L1= 10.0
L2= 5.477225575051661
Linf= 4.0 


L1= 10
L2= 5.477225575051661
m**2= 64.0 64
Linf= 4
